import type { Scenario } from '../types';

export const leoSoftstruc: Scenario = {
  id: 'leo-softstruc',
  name: 'Leo — the SoftStruc analysis',
  summary:
    'Walkthrough of the Leo SoftStruc scenario: fact phrases are highlighted and mapped to ENZ Code rules, then assembled into the three answers.',
  facts: [
    { text: 'Leo is a graduate structural engineer at a relatively small engineering consultancy, WaiStruc. He is currently working on a large commercial development, and the project is not going well. The owner and principal of WaiStruc, Dave, has taken on two large projects at once and is having problems meeting deadlines due to a lack of resources (including staff). His response when staff raise their concerns is that they should be \u2018thankful they have jobs\u2019 and that they all need to \u2018pull their weight and get on with it\u2019. Under mounting pressure, Leo is assigned to perform a dynamic load analysis for a critical part of the building\u2019s structural system, using a specialist software package SoftStruc. He only had ' },
    { text: 'a brief introduction to the software during university', tokenId: 's1' },
    { text: ' where it was a relatively minor part of a large assignment. He remembers doing well in the assignment though and getting an A for it. He ' },
    { text: 'has never used it in a professional setting, nor has he received any formal training at WaiStruc in the use of SoftStruc', tokenId: 's2' },
    { text: '. After thinking about it over lunch he ' },
    { text: 'decides to go ahead and give it a crack', tokenId: 's3' },
    { text: '. He thinks, how can he learn anything if he doesn\u2019t give things a go and he was always pretty good at picking things up. Leo runs the simulations as best he can. Things go smoothly and the results appear reasonable to him \u2014 but Leo ' },
    { text: 'isn\u2019t confident he set all the parameters correctly', tokenId: 's4' },
    { text: '. When he raises mild concerns about this with Dave, he is gruffly told: \u201cThe software basically does it for you. Don\u2019t overthink it. We need that report for the design meeting. ' },
    { text: 'Just include it', tokenId: 's5' },
    { text: '. The client is already nervous \u2014 we can\u2019t afford any more delays.\u201d Leo, feeling the pressure to perform and fearing that raising further concerns could damage his reputation and future prospects at the firm, ' },
    { text: 'decides to just write up the results in the report emails it to Dave', tokenId: 's6' },
    { text: '. At the design meeting, Dave presents the results to the clients. He states that the design work was undertaken by Leo who ' },
    { text: '\u2018is a real expert using SoftStruc', tokenId: 's7' },
    { text: ' and we are sure the design will speed up construction and reduce cost\u2019. There is no further discussion about this part of the design and the results are accepted and the meeting moves on. About three months after Leo\u2019s report was incorporated into the final structural design, construction on the commercial building is well underway. During a routine site inspection, one of the senior contractors notices ' },
    { text: 'minor cracking around a structural connection point', tokenId: 's8' },
    { text: ' \u2014 specifically an area dependent on the dynamic load calculations Leo had analysed. The cracking is unusual given the construction stage and suggests there may be unexpected stresses in the structure. The contractor raises the concern informally with Dave, who is dismissive: \u201c' },
    { text: 'It\u2019s just cosmetic. Happens all the time. Let\u2019s not open a can of worms', tokenId: 's9' },
    { text: '.\u201d Leo overhears this conversation. As he listens, he realises that if the dynamic analysis was incorrect \u2014 which he now strongly suspects it was \u2014 the structure could be experiencing forces it wasn\u2019t properly designed to withstand. Later that day, Leo quietly reopens the project files on his laptop and rechecks the software inputs he used. He quickly discovers that he ' },
    { text: 'had applied the wrong load combination factors, underestimating the actual design forces by about 20%', tokenId: 's10' },
    { text: '.' },
  ],
  steps: [
    { kind: 'annotation', tokenId: 's1', role: 'gray', tag: 'Rule 4', title: 'A module is not competence',
      body: 'A brief university exposure is not professional competence on a critical analysis. Rule 4 requires you to only undertake engineering activities within your competence.' },
    { kind: 'annotation', tokenId: 's2', role: 'warning', tag: 'Rule 4', title: 'Outside his competence',
      body: 'No professional use, no training, on a critical dynamic load analysis. This is squarely outside Leo\u2019s competence — the trigger for Rule 4.' },
    { kind: 'annotation', tokenId: 's3', role: 'pro', tag: 'Rule 4 · the choice', title: 'The decision point',
      body: 'Wanting to learn does not authorise doing critical safety work unsupervised. The competent move was to flag the limit and seek training, supervision, or peer review.' },
    { kind: 'annotation', tokenId: 's4', role: 'warning', tag: 'Rule 4', title: 'Uncertain on a critical job',
      body: 'Rule 4 also requires work be careful and competent. Being unsure the parameters are right on a critical analysis is a red flag, not a detail to wave through.' },
    { kind: 'annotation', tokenId: 's5', role: 'pro', tag: 'Pressure', title: 'Commercial pressure',
      body: '\u201cThe software does it for you\u201d is not verification. Pressure to submit unverified work never overrides the Code — the obligation stays with Leo.' },
    { kind: 'annotation', tokenId: 's6', role: 'pro', tag: 'Rule 5(a)(i)', title: 'Integrity',
      body: 'Including results he does not trust breaches honesty and integrity under Rule 5(a)(i), and the careful-and-competent duty under Rule 4.' },
    { kind: 'annotation', tokenId: 's7', role: 'pro', tag: 'Rule 4(b)(i)', title: 'Misrepresentation',
      body: 'Dave misrepresents Leo\u2019s competence to the client. Letting the \u201cexpert\u201d claim stand is permitting misrepresentation of competence — Rule 4(b)(i).' },
    { kind: 'annotation', tokenId: 's8', role: 'danger', tag: 'Rule 1', title: 'A safety signal',
      body: 'Cracking at a connection suggests unexpected stresses — a foreseeable risk to the health and safety of people. Rule 1 is engaged.' },
    { kind: 'annotation', tokenId: 's9', role: 'warning', tag: 'Rule 3', title: 'Not being managed',
      body: 'Dave\u2019s \u201cit\u2019s cosmetic, don\u2019t open a can of worms\u201d is the opposite of appropriate management. Rule 3 escalation becomes live because the matter is not being handled.' },
    { kind: 'annotation', tokenId: 's10', role: 'danger', tag: 'Rule 3', title: 'Confirmed defect',
      body: 'A 20% underestimate of design forces is an engineering matter with adverse consequences — an unacceptable likelihood of significant harm. Leo must now act, even though the error is his.' },
    { kind: 'answer', role: 'success', tag: 'Answer 1', title: 'Main issues', items: [
      'Working outside competence on a critical analysis (Rule 4).',
      'Pressure to submit work Leo did not trust; integrity compromised.',
      'Misrepresentation of Leo as an \u201cexpert\u201d to the client.',
      'A live safety risk — cracking plus a confirmed 20% error — being dismissed.',
      'Leo caused part of it, but that does not reduce his duty to act now.' ] },
    { kind: 'answer', role: 'success', tag: 'Answer 2', title: 'How the Code applies', items: [
      'Rule 4 — work only within competence, carefully; do not misrepresent or permit misrepresentation of competence.',
      'Rule 5(a)(i) — honesty and integrity; untrusted results and the \u201cexpert\u201d claim breach this.',
      'Rule 1 — safeguard health and safety; the cracking is a foreseeable risk.',
      'Rule 3 — adverse consequences; Dave dismissing it means it is not being managed, so escalate.',
      'Rule 6 — put the concern and its consequences to Dave in writing.',
      'Rule 8 — Dave\u2019s conduct may be a significant breach; consider reporting to Engineering NZ.' ] },
    { kind: 'answer', role: 'success', tag: 'Answer 3', title: 'Advise Leo to', items: [
      'Immediately re-verify the analysis, or have it independently checked.',
      'Disclose the error and its safety implication to Dave in writing (Rule 6).',
      'Make sure it reaches someone who can inspect or halt the affected work — do not let Dave bury it.',
      'If suppressed, escalate under Rule 3 to the regulator after the Rule 7 check with the employer, and weigh a Rule 8 report.',
      'Correct the record even though it exposes his mistake; acting late beats not acting. Document everything.' ] },
  ],
};
