import type { Scenario } from '../types';

export const leoSoftstruc: Scenario = {
  id: 'leo-softstruc',
  name: 'Leo — the SoftStruc analysis',
  summary:
    'Walkthrough of the Leo SoftStruc scenario: fact phrases are highlighted and mapped to ENZ Code rules, then assembled into the three answers.',
  facts: [
    { text: 'Leo, a graduate engineer at WaiStruc, is under mounting pressure from principal Dave. He is assigned a dynamic load analysis on specialist software, SoftStruc, though he only had ' },
    { text: 'a brief introduction to it at university', tokenId: 's1' },
    { text: ' and has ' },
    { text: 'never used it professionally or had any training', tokenId: 's2' },
    { text: '. He decides to ' },
    { text: 'give it a crack', tokenId: 's3' },
    { text: ' anyway. The results look plausible, but ' },
    { text: 'he is not confident he set the parameters correctly', tokenId: 's4' },
    { text: '. When he raises this, Dave says the software does it for you and to ' },
    { text: 'just include it', tokenId: 's5' },
    { text: ' for the design meeting. Leo ' },
    { text: 'writes up the results and sends them', tokenId: 's6' },
    { text: '. At the meeting Dave tells the client Leo ' },
    { text: 'is \u201ca real expert\u201d using SoftStruc', tokenId: 's7' },
    { text: '. Three months later a contractor spots ' },
    { text: 'minor cracking at a structural connection', tokenId: 's8' },
    { text: ' tied to Leo\u2019s calculations. Dave brushes it off: ' },
    { text: '\u201cit\u2019s cosmetic \u2026 let\u2019s not open a can of worms\u201d', tokenId: 's9' },
    { text: '. Leo rechecks his inputs and finds he ' },
    { text: 'used the wrong load factors, underestimating design forces by about 20%', tokenId: 's10' },
    { text: '.' },
  ],
  steps: [
    { kind: 'annotation', tokenId: 's1', role: 'gray', tag: 'Rule 4', title: 'A module is not competence',
      body: 'A brief university exposure is not professional competence on a critical analysis. Rule 4 requires you to only undertake engineering activities within your competence.' },
    { kind: 'annotation', tokenId: 's2', role: 'warning', tag: 'Rule 4', title: 'Outside his competence',
      body: 'No professional use, no training, on a critical dynamic load analysis. This is squarely outside Leo\u2019s competence — the trigger for Rule 4.' },
    { kind: 'annotation', tokenId: 's3', role: 'pro', tag: 'Rule 4 · the choice', title: 'The decision point',
      body: 'Wanting to learn does not authorise doing critical safety work unsupervised. The competent move was to flag the limit and seek training, supervision, or peer review.' },
    { kind: 'annotation', tokenId: 's4', role: 'warning', tag: 'Rule 4', title: 'Uncertain on a critical job',
      body: 'Rule 4 also requires work be careful and competent. Being unsure the parameters are right on a critical analysis is a red flag, not a detail to wave through.' },
    { kind: 'annotation', tokenId: 's5', role: 'pro', tag: 'Pressure', title: 'Commercial pressure',
      body: '\u201cThe software does it for you\u201d is not verification. Pressure to submit unverified work never overrides the Code — the obligation stays with Leo.' },
    { kind: 'annotation', tokenId: 's6', role: 'pro', tag: 'Rule 5(a)(i)', title: 'Integrity',
      body: 'Including results he does not trust breaches honesty and integrity under Rule 5(a)(i), and the careful-and-competent duty under Rule 4.' },
    { kind: 'annotation', tokenId: 's7', role: 'pro', tag: 'Rule 4(b)(i)', title: 'Misrepresentation',
      body: 'Dave misrepresents Leo\u2019s competence to the client. Letting the \u201cexpert\u201d claim stand is permitting misrepresentation of competence — Rule 4(b)(i).' },
    { kind: 'annotation', tokenId: 's8', role: 'danger', tag: 'Rule 1', title: 'A safety signal',
      body: 'Cracking at a connection suggests unexpected stresses — a foreseeable risk to the health and safety of people. Rule 1 is engaged.' },
    { kind: 'annotation', tokenId: 's9', role: 'warning', tag: 'Rule 3', title: 'Not being managed',
      body: 'Dave\u2019s \u201cit\u2019s cosmetic, don\u2019t open a can of worms\u201d is the opposite of appropriate management. Rule 3 escalation becomes live because the matter is not being handled.' },
    { kind: 'annotation', tokenId: 's10', role: 'danger', tag: 'Rule 3', title: 'Confirmed defect',
      body: 'A 20% underestimate of design forces is an engineering matter with adverse consequences — an unacceptable likelihood of significant harm. Leo must now act, even though the error is his.' },
    { kind: 'answer', role: 'success', tag: 'Answer 1', title: 'Main issues', items: [
      'Working outside competence on a critical analysis (Rule 4).',
      'Pressure to submit work Leo did not trust; integrity compromised.',
      'Misrepresentation of Leo as an \u201cexpert\u201d to the client.',
      'A live safety risk — cracking plus a confirmed 20% error — being dismissed.',
      'Leo caused part of it, but that does not reduce his duty to act now.' ] },
    { kind: 'answer', role: 'success', tag: 'Answer 2', title: 'How the Code applies', items: [
      'Rule 4 — work only within competence, carefully; do not misrepresent or permit misrepresentation of competence.',
      'Rule 5(a)(i) — honesty and integrity; untrusted results and the \u201cexpert\u201d claim breach this.',
      'Rule 1 — safeguard health and safety; the cracking is a foreseeable risk.',
      'Rule 3 — adverse consequences; Dave dismissing it means it is not being managed, so escalate.',
      'Rule 6 — put the concern and its consequences to Dave in writing.',
      'Rule 8 — Dave\u2019s conduct may be a significant breach; consider reporting to Engineering NZ.' ] },
    { kind: 'answer', role: 'success', tag: 'Answer 3', title: 'Advise Leo to', items: [
      'Immediately re-verify the analysis, or have it independently checked.',
      'Disclose the error and its safety implication to Dave in writing (Rule 6).',
      'Make sure it reaches someone who can inspect or halt the affected work — do not let Dave bury it.',
      'If suppressed, escalate under Rule 3 to the regulator after the Rule 7 check with the employer, and weigh a Rule 8 report.',
      'Correct the record even though it exposes his mistake; acting late beats not acting. Document everything.' ] },
  ],
};
